apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::758679798924:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
      rolearn: arn:aws:iam::758679798924:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-23T19:43:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1976"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f383fd6c-d856-44b3-b5c3-cbdf60380c37
